Allow to debug windows app in debug mode by setting browseinformation to true
sdatkinson/NeuralAmpModelerPlugin pull request #325
Opened 2023-07-08 21:47 UTC by fab672000

After that simple change I can step through the windows app version of the plugin.

2023-09-21 01:52 UTC, sdatkinson requested changes
Thanks for your patience.
So, in summary:

1. I'm just not sure if this is actually helping, or if you're making DRYer things that are automatically-generated (so it's a non-issue). To resolve this issue, undo the changes to `config.h` and `main.rc` that are handled by the scripts.
2. The AVX2 optimizations are nice, but covering more kinds of CPUs is more important to me than performance. To resolve this concern, a few options:
  a. If you could figure out the minimum system requirements this would create, that'd be super-helpful and woudl go a long way to helping me feel comfortable with this (seems like Haswell is already 10 years old...how time flies!) Or, if you could provide me some data points for other plugins that use AVX2, I'd feel more comfortable (It seems to me like audio plugins have a culture of aiming for really old/low-performance computers that NAM is already somewhat rocking the boat on). If I'm happy with what you find, I may approve.
  b. [My ignorance but] If this causes more than one binary to be built, and the installer picks the right one for the system it's being installed on, then I'm just all good. If you can convince me this is the case, then that'd work too 🙂 
  
Thanks again for the PR, and thanks for your patience on my review.

2023-09-21 01:52 UTC, sdatkinson commented on NeuralAmpModeler/config.h
> +#define PLUG_VERSION_MAJOR 0
I do like what you're doing here, but I'm concerned that it'll cause issues with [`bump_version.py`](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/main/bump_version.py), which I rely on.

If you want to do something like this, I'm going to need to you help walk me through why `bump_version.py` will still work (and since a lot of this is automatically-generated, I'm not sure it's a value-add. Again, have a closer look at the script.)

2023-09-21 01:52 UTC, sdatkinson commented on NeuralAmpModeler/projects/NeuralAmpModeler-aax.vcxproj
> +      <PreprocessorDefinitions>$(AAX_DEFS);EIGEN_HAS_SINGLE_INSTRUCTION_MADD;$(DEBUG_DEFS);$(EXTRA_DEBUG_DEFS);%(PreprocessorDefinitions)</PreprocessorDefinitions>
Are these optimizations going to result in a binary that might not work on everyone's CPUs?

2023-10-10 21:17 UTC, closed without merging

2023-10-10 21:17 UTC, fab672000 commented
not worth spending too much time on this at this point, there are better improvements to offer.